version: '3'

services:
  django-postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=andreve
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data

  django-pgadmin4:
    image: dpage/pgadmin4
    depends_on:
        - django-postgres
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.local
      - PGADMIN_DEFAULT_PASSWORD=password
volumes:
  postgres:
  



